version: '3.9'

services:
  kafka:
    image: 'bitnami/kafka:3.2.3'
    ports:
      - '9092:9092'
    volumes:
      - './kafka:/bitnami'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_BROKER_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=5S96r9sgSi6IEA1MP_Ze2A
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka-ui:
    image: 'provectuslabs/kafka-ui'
    ports:
      - '8090:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
    depends_on:
      - kafka
  postgres:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - '${POSTGRES_VOLUME:-./postgres}:/var/lib/postgresql/data'
  keycloak:
    image: 'quay.io/keycloak/keycloak:23.0.3'
    ports:
      - '8100:8080'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: "postgres"
      DB_DATABASE: "keycloak"
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_SCHEMA: "public"
      DB_PASSWORD: ${POSTGRES_PASSWORD:-test}
      KC_HOSTNAME: "localhost"
      KEYCLOAK_ADMIN: "sadmin@swe.brown.com"
      KEYCLOAK_ADMIN_PASSWORD: "nimdas"
    command: start-dev --import-realm
    volumes:
      - type: bind
        source: ${KEYCLOAK_IMPORT_DIR:-./docs/keycloak}
        target: /opt/keycloak/data/import
  exam-manage-service:
    image: ghcr.io/se-brown-2023/automated-testing-applicants-service/manage-service:latest
    ports:
      - "8080:8080"
    volumes:
      - './manage-service:/etc/swe2023brown/exam-manage-service/'
      - './manage-service/logs:/var/logs/swe2023brown/exam-manage-service/'
    depends_on:
      - postgres
  exam-judging-service:
    image: ghcr.io/se-brown-2023/automated-testing-applicants-service/judging-service:latest
    ports:
      - "8010:8010"
    volumes:
      - './judging-service:/etc/swe2023brown/exam-judging-service/'
      - './judging-service/logs:/var/log/swe2023brown/exam-judging-service/'
    depends_on:
      - postgres
      - kafka
  exam-conduct-service:
    image: ghcr.io/se-brown-2023/automated-testing-applicants-service/conduct-service:latest
    ports:
      - "8020:8020"
    volumes:
      - './conduct-service:/etc/swe2023brown/exam-conduct-service/'
      - './conduct-service/logs:/var/logs/swe2023brown/exam-conduct-service/'
    depends_on:
      - postgres
      - kafka
  frontend:
    image: ghcr.io/se-brown-2023/automated-testing-applicants-service/frontend-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - exam-conduct-service
      - exam-judging-service
      - exam-manage-service
