server:
  port: ${port:8000}
  shutdown: graceful

spring:
  application:
    name: exam-manage-service
  config:
    import: application-db.yml
  datasource:
    url:
    username:
    password:

graylog:
  server:

logging:
  file:
    name: ${log.dir:/tmp}/exam-manage-service.main.log

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
