spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atas?reWriteBatchedInserts=true
    username: postgres
    password: test
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.sebrown2023.model.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      client-id: ${spring.application.name}
      security:
        protocol: PLAINTEXT

kafka:
  backoff:
    delay: 3000
    retry: 3

compilers:
  compilerSettingsMap:
    JAVA:
      executionThreads: 1
