server:
  port: ${port:8010}
  shutdown: graceful

spring:
  application:
    name: exam-judging-service
  config:
    import: application-db.yml
  datasource:
    url:
    username:
    password:
  kafka:
    bootstrap-servers:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.sebrown2023.model.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      client-id: ${spring.application.name}
      security:
        protocol:

submissionService:
  executionThreads:

java-compiler:
  lib-dir:

logging:
  file:
    name: ${log.dir:/tmp}/exam-judging-service.main.log