server:
  port: ${port:8010}
  shutdown: graceful

spring:
  application:
    name: exam-judging-service
  # Database
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 50
      connectionTimeout: 40000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_ddl: false
        ddl_auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        flush-mode: manual
        jdbc:
          batch_size: 500
  kafka:
    bootstrap-servers:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.sebrown2023.model.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      client-id: ${spring.application.name}
      security:
        protocol:


logging:
  file:
    name: ${log.dir:/tmp}/exam-judging-service.main.log