spring:
  # Database
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connectionTimeout: 40000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_ddl: false
        ddl_auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        flush-mode: manual
        jdbc:
          batch_size: 500
