server:
  port: ${port:8020}
  shutdown: graceful

spring:
  application:
    name: exam-conduct-service
  config:
    import: application-db.yml
  datasource:
    url:
    username:
    password:
    driver-class-name:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swe-brown-2023-realm
      client:
        registration:
          keycloak:
            client-id: automated-testing-applicants-service
            authorization-grant-type: authorization_code
            scope: openid
            clientId: automated-testing-applicants-service
            clientSecret: P3mSHqKJLPrav1nv0daXlsbVDpsYg7sj
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/swe-brown-2023-realm
            user-name-attribute: preferred_username
            tokenUri: http://localhost:8080/realms/swe-brown-2023-realm/protocol/openid-connect/token

cors:
  frontend:
    url:

graylog:
  server:

logging:
  file:
    name: ${log.dir:/tmp}/exam-conduct-service.main.log
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
