server:
  port: ${port:8020}
  shutdown: graceful

spring:
  application:
    name: exam-conduct-service
  config:
    import: application-db.yml
  datasource:
    url:
    username:
    password:

graylog:
  server:

logging:
  file:
    name: ${log.dir:/tmp}/exam-conduct-service.main.log