server:
  port: ${port:8020}
  shutdown: graceful

spring:
  application:
    name: exam-conduct-service
  config:
    import: application-db.yml
  datasource:
    url:
    username:
    password:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.sebrown2023.model.dto"

cors:
  frontend:
    url:

graylog:
  server:

logging:
  file:
    name: ${log.dir:/tmp}/exam-conduct-service.main.log
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true