name: Build exam manage service

on:
  push:
    branches: master
    paths:
      - exam-manage-service/**
      - common/**
      - .github/workflows/build.exam-manage-service.yml
  pull_request:
    branches: master
    paths:
      - exam-manage-service/**
      - common/**
      - .github/workflows/build.exam-manage-service.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: zulu
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :exam-manage-service:build
